Added Filmpertutti Provider (it)
LagradOst/CloudStream-3 pull request #1195
Opened 2022-06-18 23:47 UTC by antonydp

I needed to add the domain MixDropTo.
I also added the quality tag to Cineblog.

In tantifilm I defined and used unshorten_linkup, but, if I will ever finish coding the UnshortenIt Class, that function would be moved in utils

2022-06-19 00:51 UTC, LagradOst requested changes
Kotlin is a null safe language, that also means it has a lot of tools for making it easy to work with null. 

a simple way is to cascade the null with the ?. operator, this operator simple means that if the current object will be null and not throw an error.

a = b?.c    a will be null if b or c is null
a = b!!.c   a will be null if c is null and crash if b is null, you dont want this
you can chain them too
a = b?.c?.d?.e    ect

you can also do

a = b?.let { B ->
...    code here will be 100% sure that B is not null
} ?: run {
...    code here knows that b is null
}

2022-06-19 00:51 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +            val quality = if (qualitydata!= null) {
?.

2022-06-19 00:51 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +            descipt0.parent()!!.nextSibling()!!.toString().parseAsHtml().toString()
?.

2022-06-19 00:51 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +        val year = if (year0!= null){
?.

2022-06-19 00:51 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +        val trailerurl = if (document.selectFirst("div.youtube-player")!=null){
?.

2022-06-19 00:51 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +        val trailerurl = if (document.selectFirst("div.youtube-player")!=null){
?.let {} ?:  also exist

2022-06-19 00:51 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +                    val epTitle = if(episode.selectFirst("li.other_link > a") != null) {
?.

2022-06-19 00:51 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +            val urls = if (urls0.size != 0){
isNotEmpty

2022-06-19 00:51 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +                document.select("#info > ul > li ").map { it.selectFirst("a")!!.attr("href") }.toString()
remove toString

2022-06-19 00:51 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +        if (uri.contains("/tv/")) {
when case

2022-06-19 07:34 UTC, antonydp commented
Fantastic! Thanks a lot for the tips, I was wondering how to do those checks in a better way

2022-06-19 09:24 UTC, antonydp commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +                document.select("#info > ul > li ").map { it.selectFirst("a")!!.attr("href") }.toString()
here I did the tostring because filmpertutti lists all links of all episodes / movie on the same page.
![image](https://user-images.githubusercontent.com/38143733/174474289-79eba355-8189-4e7c-9a17-89ea20e44ec4.png)

I collect all the links of a given episode and I place them in a list, witch I give to data as a string (here the .tostring()).
In the load function then i split the links again with .split(",") and call loadExtractor on each of them separately.

Is there a better canonical way to handle this situations?

2022-06-19 09:27 UTC, antonydp commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +        val year = if (year0!= null){
it's good like that?
`val year = (document.selectFirst("i.fa.fa-calendar.fa-fw")?.parent()?.nextSibling() as Element)
            .text().substringAfterLast(" ").filter { it.isDigit() }.toInt()`

2022-06-19 10:00 UTC, antonydp commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +        val year = if (year0!= null){
here I did this way:
`val year =
            document.selectFirst("#content > h1")!!.text().substringAfterLast("(").filter { it.isDigit() }.toIntOrNull() ?:
            description.substringAfter("trasmessa nel").take(6).filter { it.isDigit() }.toIntOrNull() ?:
            (document.selectFirst("i.fa.fa-calendar.fa-fw")?.parent()?.nextSibling() as Element).text().substringAfterLast(" ").filter { it.isDigit() }.toInt()
`

since I notices that the pubblication year reported is not always the year of the movie i first checked if there's the year in the title, then if there is on the description and finally in the pubblication infos

2022-06-19 13:40 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +                document.select("#info > ul > li ").map { it.selectFirst("a")!!.attr("href") }.toString()
Yes, the proper way is to convert a list of strings to JSON and in loadLinks turn it back to a List\<String\>. This makes the code a lot more readable as you are working with real types and not just a string.

2022-06-19 13:47 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +                document.select("#info > ul > li ").map { it.selectFirst("a")!!.attr("href") }.toString()
> Yes, the proper way is to convert a list of strings to JSON and in loadLinks turn it back to a List<String>. This makes the code a lot more readable as you are working with real types and not just a string.

Check out .toJson() parseJson<T>(string) and tryParseJson<T>(string) <- tryParseJson will wrap parseJson in a try catch block and return null

2022-06-19 21:35 UTC, antonydp commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +                document.select("#info > ul > li ").map { it.selectFirst("a")!!.attr("href") }.toString()
it works, thanks for the help

2022-06-19 21:36 UTC, antonydp commented
I think I've fixed every problem,
if it's good now I'm ready to merge!

2022-06-19 23:20 UTC, LagradOst reviewed
👍 Very good changes, here are some final improvements

2022-06-19 23:20 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +        val trailerurl = document.selectFirst("div.youtube-player").let{ urldata->
I would do `document.selectFirst("div.youtube-player")?.attr("data-id")?.let`

2022-06-19 23:20 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +                    val posterUrl = episode.selectFirst("figure > img")!!.attr("data-src")
?.

2022-06-19 23:20 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +            else{ document.select("#info > ul > li ").map { it.selectFirst("a")!!.attr("href") }.toJson() }
`mapNotNull { it.selectFirst("a")?.attr("href")  }`

2022-06-19 23:20 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +            (uri.contains("/ga/") || uri.contains("/ga2/")) -> uri = Base64.decode(uri.split('/').last().toByteArray(), Base64.DEFAULT).decodeToString().trim()
use the built in base64 decoder (base64Decode)

2022-06-19 23:20 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +            uri = short[0]
if you are going to regex all occurrences, but only use the first result, then it is better to use find

2022-06-19 23:20 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +            document.selectFirst("#content > h1")!!.text().substringAfterLast("(").filter { it.isDigit() }.toIntOrNull() ?:
document.selectFirst("#content > h1")!! <---- replace with ?.

2022-06-19 23:20 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +            document.selectFirst("#content > h1")!!.text().substringAfterLast("(").filter { it.isDigit() }.toIntOrNull() ?:
then add ?. to the following .

2022-06-19 23:20 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +            uri = short[0]
same is for the Regex usage right above this

2022-06-19 23:20 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +                        getQualityFromString(qualitydata.text())
`val quality = getQualityFromString(it.selectFirst("div.hd")?.text())`

2022-06-19 23:20 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/FilmpertuttiProvider.kt
> +        val trailerurl = document.selectFirst("div.youtube-player").let{ urldata->
because rn it can return "https://www.youtube.com/watch?v=null"

2022-06-20 13:04 UTC, LagradOst approved these changes
Very nice :+1: 

Ready to merge?

2022-06-20 14:02 UTC, antonydp commented
yes! Thanks again for the tips!

2022-06-20 14:29 UTC, merged