New source with content in Latin Spanish
LagradOst/CloudStream-3 pull request #369
Opened 2021-12-25 20:57 UTC by JonaxHS

Hello, I have added the page pelisplus that handles movies and series in Spanish, it is a vidstream clone but with some modifications in the template, some content extractor urls are different, several classes were added for that. Excuse me, my English, I'm Mexican.

2021-12-25 21:53 UTC, Blatzar reviewed
Looks good

2021-12-25 21:53 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/PelisplusProviderTemplate.kt
> +open class PelisplusProviderTemplate : MainAPI() {
This class looks very much like VidstreamProviderTemplate, is it possible to inherit from that class instead of copy pasting the code?

2021-12-25 21:54 UTC, LagradOst requested changes
Some stuff that needs changed

2021-12-25 21:54 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/extractors/Pelisplus.kt
> +open class Pelisplus(val mainUrl: String) {
vidstream was updated like 1 commit ago, you need to update this

2021-12-25 21:54 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/extractors/WatchSB1.kt
> +class WatchSB1 : WatchSB() {
This already exists in cs3

2021-12-25 21:54 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/PelisplusProviderTemplate.kt
> +    private fun fixUrl(url: String): String {
remove this and use the built in version

2021-12-25 21:54 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/PelisplusProviderTemplate.kt
> +        val episodes = soup.select(".listing.items.lists > .video-block").withIndex().map { (_, li) ->
is withIndex necessary?

2021-12-25 21:54 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/PelisplusProviderTemplate.kt
> +open class PelisplusProviderTemplate : MainAPI() {
override langauge to "es" because this is a spanish provider

2021-12-25 21:54 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/PelisplusProviderTemplate.kt
> +            val poster = li.selectFirst("img")?.attr("src")?.replace("//img", "https://img")
use fixurl

2021-12-25 21:54 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/PelisplusProviderTemplate.kt
> +open class PelisplusProviderTemplate : MainAPI() {
*Feel free to modify VidstreamProviderTemplate to make it more general if needed

2021-12-25 23:49 UTC, JonaxHS commented on app/src/main/java/com/lagradost/cloudstream3/extractors/WatchSB1.kt
> +class WatchSB1 : WatchSB() {
Sorry, is that each extractor has a different url, I'll see if I can implement the 2 urls in a single file

2021-12-26 17:45 UTC, LagradOst commented
@JonaxHS I made a pr on your pr to fix stuff

2021-12-27 17:35 UTC, JonaxHS commented
> @JonaxHS I made a pr on your pr to fix stuff

Ready already combine the PR

2021-12-27 17:41 UTC, LagradOst approved these changes

2021-12-27 17:41 UTC, merged