New anime site with spanish subtitles
LagradOst/CloudStream-3 pull request #382
Opened 2021-12-30 08:59 UTC by Stormunblessed

I saw the pr made by @JonaxHS made and it reminded me of an anime site, I went to try the code and it worked, this is the result.

pd: I'm a newbie at this, so I think there might be some things to fix.

2021-12-30 12:54 UTC, LagradOst commented
LGTM, @Blatzar thoughts

2021-12-30 14:43 UTC, Blatzar requested changes

2021-12-30 14:43 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimeIDProviderTemplate.kt
> +open class AnimeIDProviderTemplate : MainAPI() {
Is this entire class necessary? It seems like a copy of https://github.com/LagradOst/CloudStream-3/blob/master/app/src/main/java/com/lagradost/cloudstream3/movieproviders/VidstreamProviderTemplate.kt

Can't you just do 
```kotlin
class AnimeIDProvider : VidstreamProviderTemplate()
```
And discard this class?

If that's isn't possible then make VidstreamProviderTemplate more abstract and put needed css selectors as variables.

2021-12-30 14:43 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimeIDProviderTemplate.kt
> +open class AnimeIDProviderTemplate : MainAPI() {
(Dont forget to put override val lang = "es" in AnimeIDProvider)

2022-01-04 01:11 UTC, Stormunblessed commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimeIDProviderTemplate.kt
> +open class AnimeIDProviderTemplate : MainAPI() {
It works with `VidstreamProviderTemplate` but it's mostly aesthetics changes that I made in `AnimeIDProviderTemplate` since the first one is in english, Copy pasting it was the easy way for me, because I'm still learning kotlin

2022-01-07 13:39 UTC, LagradOst commented
This wont be accepted, this is taken from https://github.com/ArjixWasTaken/CloudStream-3/blob/master/app/src/main/java/com/ArjixWasTaken/cloudstream3/animeproviders/CrunchyrollProvider.kt and Crunchyroll wont be accepted due to DMCA risk

2022-01-07 13:40 UTC, closed without merging