Added italian translation
LagradOst/CloudStream-3 pull request #504
Opened 2022-01-23 16:06 UTC by Yoddikko

2022-01-23 16:22 UTC, Blatzar commented on app/src/main/res/values-it/strings.xml
> +    <string name="subtitles_depressed">Depresso</string>
You don't need to change anything if you want, but just pointing out.

The English translation should probably be 'Lowered' instead of 'Depressed', but isn't since we forgot to fix. It should basically the opposite of subtitles_raised based on how the effect looks.
 
Take a look at settins > subtitles > edge type > depressed

and see if you got a good word for that effect.

2022-01-23 16:23 UTC, Blatzar commented
I will fix readme and settings soon :+1: 
looks good otherwise

2022-01-23 16:35 UTC, LagradOst commented
/home/runner/work/CloudStream-3/CloudStream-3/app/src/main/res/values-it/strings.xml:378:3: Error: The element type "string" must be terminated by the matching end-tag "</string>".

2022-01-25 07:59 UTC, C10udburst requested changes

2022-01-25 07:59 UTC, C10udburst commented on app/src/main/res/values-it/strings.xml
> +    <string name="year_format" translatable="false" formatted="true">%d</string>
maybe remove all entries with `translatable="false"` for better clarity

2022-01-30 18:25 UTC, LagradOst commented
Should this be merged?

2022-01-30 19:27 UTC, Blatzar commented
Yes :+1:

2022-01-30 19:29 UTC, merged