Fixes on multiple providers and added some extractors
LagradOst/CloudStream-3 pull request #734
Opened 2022-03-01 23:34 UTC by Stormunblessed

2022-03-02 12:23 UTC, LagradOst requested changes
1. Use parseJson and not mapper
2. ONLY use apmap for parallel network operations
3. Use loadExtractor
4. Check if USER_AGENT works

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/CuevanaProvider.kt
> +        val year = if (yearf.isEmpty()) null else yearf.first().toIntOrNull()
I think you can do firstOrNull()?.toIntOrNull()

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/CuevanaProvider.kt
> +        val year = if (yearf.isEmpty()) null else yearf.first().toIntOrNull()
or you simply do find to get the first, so you dont index all spans just to select the first one

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/CuevanaProvider.kt
> +                    val json = mapper.readValue<Femcuevana>(url)
parseJson is preferred to use, in case we change framework

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/CuevanaProvider.kt
> +                                    for (extractor in extractorApis) {
use loadExtractor

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/CuevanaProvider.kt
> +                        for (extractor in extractorApis) {
use loadExtractor

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/CuevanaProvider.kt
> +                                    for (extractor in extractorApis) {
use loadExtractor

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/PeliSmartProvider.kt
> +                if (it.startsWith(extractor.mainUrl)) {
use loadExtractor

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/PelisplusHDProvider.kt
> +        }.toList()
toList is not needed

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/PelisplusHDProvider.kt
> +                for (extractor in extractorApis) {
use loadExtractor

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/CuevanaProvider.kt
> +                e.printStackTrace()
use logError

2022-03-02 12:23 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/EntrePeliculasySeriesProvider.kt
> +                "Capítulo $episode",
it is preferred to use name or if that is not found return null. that way the "Episode text" wont be hardcoded

2022-03-03 11:51 UTC, Stormunblessed commented
I don't get it, it's works

2022-03-03 13:06 UTC, LagradOst requested changes
Use css selectors when you can, if that does not work then use regex but if you are only intrested in the first result, then use find and not findall. 

map does not need to be transformed into a list to chain another map or apmap to it.

if a name on an episode is not specified leave it null, dont hardcode it like "Episode $epNum" as the app takes care of that and uses the proper translation

2022-03-03 13:06 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/CinecalidadProvider.kt
> +        println(data)
remove println

2022-03-03 13:06 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/BflixProvider.kt
> +        else durationregex.findAll(durationdoc).map {
cant this be done with css selectors, if not dont use findAll

2022-03-03 13:06 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimeflvProvider.kt
> +                }.toList().apmap {
remove .toList()

2022-03-04 12:39 UTC, LagradOst commented
LGTM 👍 
Ready to merge?

2022-03-04 12:47 UTC, merged