[Provider] TheFlix.to
LagradOst/CloudStream-3 pull request #829
Opened 2022-03-20 14:06 UTC by Stormunblessed

2022-03-20 15:30 UTC, LagradOst requested changes

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +        val movieId = if (tvtype == TvType.Movie) pageMain.movie?.id else
make a bool for isMovie and do that instead of repearing == TvType.Movie 10 times

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +        if (available == false) throw ErrorLoadingException(typetext)
do !available, and place typetext inside that scope so `if(!available) {
val typetext = if (isMovie) "This movie is not available on the site."
        else "This tv show has no episodes available on the site."
throw ErrorLoadingException(typetext)
}`

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +    override suspend fun load(url: String): LoadResponse? {
It looks like pageMain.selectedTv and pageMain.movie has a lot in common, you might want to invest into a interface that both has so you can simply do `val metadata : ITheFlixMetadata? = if(isMovie) pageMain.movie else  pageMain.selectedTv` 
then you can remove like all if statments as pageMain.movie and pageMain.selectedTv contain the same things

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +                    actors = castlist,
use addActors instead it has multible wrapper input types like plain Actor, https://github.com/LagradOst/CloudStream-3/blob/75ec12b02ce231a956684617468c8da822e7ba11/app/src/main/java/com/lagradost/cloudstream3/MainAPI.kt#L642

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +                    actors = castlist,
(you have to use newMovieLoadResponse)

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +                    actors = castlist,
you can even do a plain string list https://github.com/LagradOst/CloudStream-3/blob/75ec12b02ce231a956684617468c8da822e7ba11/app/src/main/java/com/lagradost/cloudstream3/MainAPI.kt#L627

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +            val link = if (tvtype == TvType.Movie) "$mainUrl/movie/${loadDocs.id}-${cleanTitle(title)}"
I think this might be a bug right? 
tvtype is refering to the top level item, it has nothing to do with recommendations

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +    data class LoadPageProps (
All data class in this file can be changed to val to indicate that they dont change after parsing

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +                            val isMovie = link.contains("movie")
do typeinfo == TvType.Movie instead

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +class TheFlixToProvider : MainAPI() {
You might also want to include this in providers.json
https://github.com/LagradOst/CloudStream-3/blob/master/providers.json

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +                    if (test.isEmpty()) {
invert

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +        val script = doc.select("script[type=application/json]").map { it.data() }.first()
use selectFirst

2022-03-20 15:30 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +        val scripttext = soup.select("script[type=application/json]").map { it.data() }.first()
use selectFirst

2022-03-21 08:49 UTC, Stormunblessed commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/TheFlixToProvider.kt
> +            val link = if (tvtype == TvType.Movie) "$mainUrl/movie/${loadDocs.id}-${cleanTitle(title)}"
I need tvtype here to get a valid link

2022-03-21 11:27 UTC, LagradOst commented
Really nice changes, looks much cleaner now :+1: ready to merge?

2022-03-21 11:28 UTC, Stormunblessed commented
> Really nice changes, looks much cleaner now :+1: ready to merge? 

Yeah

2022-03-21 12:12 UTC, merged