Added provider AnimePahe
LagradOst/CloudStream-3 pull request #9
Opened 2021-08-17 20:36 UTC by ArjixWasTaken

2021-08-17 20:37 UTC, ArjixWasTaken commented
It works as is.
Should I also add "Random Anime" to the homepage?
I can pick like 15 random anime, and show them in a list.

2021-08-17 20:49 UTC, ArjixWasTaken commented
I guess the kwik sorcery could be moved to a separate extractor.
But I had a bad experience making one and I don't want to touch that code.

If you want to you can convert the kwik code to an extractor.
Although I can't think of any site other than AnimePahe that uses kwik....

2021-08-17 20:50 UTC, ArjixWasTaken commented
And uh....how do you do that homepage thingy with the huge slideshow of movies/shows in trailers.to and wcostream?

2021-08-17 20:56 UTC, LagradOst reviewed
Not provider sufix?

2021-08-17 21:11 UTC, ArjixWasTaken commented
> Not provider sufix?

uh

2021-08-17 21:12 UTC, ArjixWasTaken commented
You saw nothing

2021-08-17 22:19 UTC, Blatzar requested changes

2021-08-17 22:19 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +        val KWIK_PARAMS_RE = """\(\"(\w+)\",\d+,\"(\w+)\",(\d+),(\d+),\d+\)""".toRegex()
Not `Regex("""\(\"(\w+)\",\d+,\"(\w+)\",(\d+),(\d+),\d+\)""")` :pensive:

2021-08-17 22:19 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +                YOUTUBE_VIDEO_LINK.find(html)?.destructured?.component1()
pretty sure you can just do 
```kotlin
val (trailer): String? = if (html.contains("https://www.youtube.com/watch")) {
                YOUTUBE_VIDEO_LINK.find(html)?.destructured
```

2021-08-17 22:19 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +            e.printStackTrace()
Use normalSafeApiCall

2021-08-17 22:19 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +    private fun pow(base: Int, expo: Int): Long{
try with build in pow and see if it works :pray:

2021-08-17 22:19 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +        while (responseCode != 200) {
not keen on risking an infinite request loop, add a max if you haven't and i missed it

2021-08-17 22:19 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +                cookies=cookieStrToMap(fContent.headers.getValue("set-cookie").replace("path=/,", ""))
can't you do `fContent = khttp.get(bypassAdf..... ).cookies` and then pass it in a second khttp request without anything else?

2021-08-17 22:23 UTC, ArjixWasTaken commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +        val KWIK_PARAMS_RE = """\(\"(\w+)\",\d+,\"(\w+)\",(\d+),(\d+),\d+\)""".toRegex()
virtually no difference but ok

2021-08-17 22:23 UTC, ArjixWasTaken commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +                YOUTUBE_VIDEO_LINK.find(html)?.destructured?.component1()
shh

2021-08-17 22:27 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +            e.printStackTrace()
> 
> 
> Use normalSafeApiCall

but no, that should be handled for you, you should not use try catch in the providers if you dont want to display a specified error message

2021-08-17 22:30 UTC, ArjixWasTaken commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +                YOUTUBE_VIDEO_LINK.find(html)?.destructured?.component1()
uhh, remove the if statement then

2021-08-17 22:30 UTC, Blatzar commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +            e.printStackTrace()
Need to steal that safety for Shiro

2021-08-17 22:30 UTC, ArjixWasTaken commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +            e.printStackTrace()
kk

2021-08-17 22:31 UTC, ArjixWasTaken commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +        while (responseCode != 200) {
I'll make it 20 then.
It rarely goes above 2 iterations.

2021-08-17 22:35 UTC, ArjixWasTaken commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +                cookies=cookieStrToMap(fContent.headers.getValue("set-cookie").replace("path=/,", ""))
uhh, no

2021-08-17 22:42 UTC, ArjixWasTaken commented on app/src/main/java/com/lagradost/cloudstream3/animeproviders/AnimePaheProvider.kt
> +                YOUTUBE_VIDEO_LINK.find(html)?.destructured?.component1()
fucking fails

2021-08-18 00:20 UTC, ArjixWasTaken commented
Ok fixed a bug with the episode link generation.
(kotlin int ranges are weird, `0..10` will be 11 iterations...)

2021-08-18 00:21 UTC, merged