[Feature] Add setting to Truncate Video title on Player
LagradOst/CloudStream-3 pull request #918
Opened 2022-04-07 11:52 UTC by Jacekun

Feature requested on discord.
Ready for merge.

2022-04-07 12:50 UTC, LagradOst requested changes
I do not understand why you want this option. If you want to add it I would also suggest an option to simply turn of the title and inf title length. Also check out android:maxLength="[PUT VALUE HERE]"

2022-04-07 12:50 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/GeneratorPlayer.kt
> +        val settingsManager = PreferenceManager.getDefaultSharedPreferences(requireContext())
do not use requireContext(), IT WILL crash

2022-04-07 12:50 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/GeneratorPlayer.kt
> +        val settingsManager = PreferenceManager.getDefaultSharedPreferences(requireContext())
use context?.let or smth

2022-04-07 12:50 UTC, LagradOst commented on app/src/main/res/xml/settings.xml
> +            android:icon="@drawable/ic_baseline_letter_a" />
DO NOT USE .PNG use vector images instead, check out https://fonts.google.com/icons?selected=Material+Icons or use the built in vector image in android studio

2022-04-07 12:50 UTC, LagradOst commented on app/src/main/res/values/array.xml
> +        <item>None</item>
There is a  @ string/none

2022-04-10 03:38 UTC, Jacekun commented
> I do not understand why you want this option. If you want to add it I would also suggest an option to simply turn of the title and inf title length. Also check out android:maxLength="[PUT VALUE HERE]"

I personally isn't bother by long titles. This feature is requested by someone on discord and I thought "Why not?" since its possible to be implemented. Also, I'd rather have the setting decide the length than a hardcoded value so users can control how long the title should be on the player UI.

2022-04-10 18:08 UTC, LagradOst commented
No, I meant that you can use `.filters = arrayOf(InputFilter.LengthFilter(length))` and android will truncate the text. Also what do you think about adding the option of not display the title, or is that not necessary?

2022-04-10 21:33 UTC, LagradOst commented on app/src/main/res/drawable/ic_baseline_text_format_24.xml
> +    android:tint="?attr/colorControlNormal">
?attr/white

2022-04-12 12:23 UTC, merged

2022-04-12 14:31 UTC, MrConqueror commented
What a useless feature, why not remove Video info quality. Ask shivam for help to do it. Because he did it on his app. We've been asking this so we thought devs of this app can't do it. That's why they're ignoring this feature