Added Nginx Provider and Nginx settings
LagradOst/CloudStream-3 pull request #932
Opened 2022-04-09 13:07 UTC by Sarlay

I added Nginx Provider (which you must self host)
It means that only you can access your server which is hosting your own files
I'll write a tutorial if you are interested

2022-04-09 13:42 UTC, LagradOst requested changes
Nice, providers :+1:. However can you hide it when you are not logged in? It will confuse users and may open by random on first launch, making them think you need nginx.

Also any code that runs at startup need to be crash safe, always assume android will crash at any time

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/MainAPI.kt
> +    @JsonProperty("credentials") var credentials: String = "None",
I would like if it was nullable instead of None

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/MainAPI.kt
> +    open var storedCredentials = "NONE"
same here, if it is not required then it should be null

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> +	fun addToJson(data : java.util.HashMap<String, ProvidersInfoJson>) : java.util.HashMap<String, ProvidersInfoJson> {
please wrap this inside a try catch or normalsafeapicall because android will crash when context is involved and you dont want to lock users out from the app because this runs on startup

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> +    fun createJson(data : String) : ProvidersInfoJson { //java.util.HashMap<String, ProvidersInfoJson>
same here, try catch/normalsafeapicall

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> +            val NginxProviderName = NginxProvider().name
try catch

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +    override var storedCredentials: String = "null, test lmao"
set to null

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +        println("using getAuthHeader: $storedCredentials")
println should not be present in any provider as it is only used for debugging and errors bubble up, if this is needed then use Log.i(name, "message")

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +        println("gettingmainurl: $mainUrl")
same here

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/utils/SingleSelectionHelper.kt
> +        fun Activity.showNginxTextInputDialog(
Can you add nullable paramater for input type, in this case you can set the input type to url and that will make the keyboard not automaticly place space after dot ect.

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/utils/SingleSelectionHelper.kt
> +        fun Activity.showNginxTextInputDialog(
https://developer.android.com/training/keyboard-input/style

2022-04-09 13:42 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/utils/SingleSelectionHelper.kt
> +        println(value)
remove print

2022-04-09 14:52 UTC, LagradOst commented
episodes are different, now use newEpisode or just Episode

2022-04-09 17:27 UTC, Sarlay commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +        println("using getAuthHeader: $storedCredentials")
oh yeah I just forget about those println from debugging

2022-04-09 17:31 UTC, Sarlay commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +    override var storedCredentials: String = "null, test lmao"
Do I also set the mainUrl to null ?
That would require to change it in MainAPI.kt too (not a problem for me but idk)

2022-04-09 22:26 UTC, Sarlay commented
I'll update that tomorrow since you are still working on it

2022-04-10 17:43 UTC, LagradOst reviewed
Smaller quality of code changes 👍

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> +            return null
this should return data not null

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> +                data[NginxProvider().javaClass.simpleName] = ProvidersInfoJson(
you init NginxProvider() a lot here, I would suggest to have a variable called provider = NginxProvider()

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> +    fun createJson() : ProvidersInfoJson? { //java.util.HashMap<String, ProvidersInfoJson>
rename to smth fitting like createNginxJson

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +    override var mainUrl = "null"  // TO CHANGE
simply dont override it if it is none

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +    override var storedCredentials: String? = null
you dont need to override it

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +            return TvSeriesLoadResponse(
I would suggest using newTvSeriesLoadRespnse to not have as much null

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +                                    null,
you can remove these trailing nulls

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsFragment.kt
> +                16,
use android.text.InputType.TYPE_TEXT_VARIATION_URI instead for readability

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsFragment.kt
> +                16,
TYPE_TEXT_VARIATION_URI

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/utils/SingleSelectionHelper.kt
> +            { callback.invoke(it) },
can you simply pass the callback?

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/res/layout/bottom_input_dialog.xml
> +<?xml version="1.0" encoding="utf-8"?>
you might want to add nextNavigationDown ect to be able to use this on a tv

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +                if (episodes.isNotEmpty()) {
this line should not be necessary

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +            val description = metadataDocument.selectFirst("plot").text()
duplicate code you can have above the if statment

2022-04-10 17:43 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +        if (mainUrl == "null"){
replace with NONE if you remove mainurl override

2022-04-10 18:07 UTC, Sarlay commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +    override var storedCredentials: String? = null
but I added it as `open var` in MainAPI.kt and now I get 
`storedCredentials' hides member of supertype 'MainAPI' and needs 'override' modifier`

2022-04-10 21:29 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +    override var storedCredentials: String? = null
try `open var storedCredentials : String? = null`

2022-04-10 21:31 UTC, LagradOst commented on app/src/main/java/com/lagradost/cloudstream3/movieproviders/NginxProvider.kt
> +    override var mainUrl = "null"  // TO CHANGE
aka remove this line

2022-04-11 10:29 UTC, LagradOst commented
LGTM, however I have one question. "Click to see a Nginx setup guide" it does nothing when I click. did you forget to do smth like https://github.com/LagradOst/CloudStream-3/blob/d4ddab83e46035eb585200fc0ee8f8405abc88be/app/src/main/res/xml/settings.xml#L250

2022-04-11 14:51 UTC, Sarlay commented
I wanted to write a guide about how to install and use that feature on my website (and how I host the media files) but idk do you mind if I do that ?
I can add the link to the tutorial only my fork it's not a huge deal

2022-04-11 14:55 UTC, LagradOst commented
Remove the text or link it to a tutorial page

2022-04-11 15:37 UTC, Sarlay commented
Ok I added a link my website

2022-04-11 20:14 UTC, Sarlay commented
Yes I am ready 👍

2022-04-11 20:17 UTC, merged